<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Car;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        Car::insert([
            [
                'brand' => 'Škoda',
                'model' => 'Yeti 1.2 FSI',
                'year' => 2013,
                'price_per_day' => 23.00,
                'transmission' => 'Automatski',
                'fuel' => 'Benzin',
                'category' => 'Malo vozilo',
                'featured' => true,
                'image' => 'uploads/cars/skoda_yeti1.jpg',
                'description' => 'Škoda Yeti 1.2 je kompaktni SUV koji spaja praktičnost i udobnost, idealan za gradske vožnje i povremene avanture van puta.',
            ],
            [
                'brand' => 'Škoda',
                'model' => 'Fabia 1.2 FSI',
                'year' => 2021,
                'price_per_day' => 19.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Benzin',
                'category' => 'Malo vozilo',
                'featured' => false,
                'image' => 'uploads/cars/skoda_fabia1.jpg',
                'description' => 'Škoda Fabia 1.2 FSI kombinuje praktičnost i štedljivost u svakodnevnoj vožnji, pružajući vozačima agilnost i udobnost uz pristupačne troškove održavanja.',
            ],
            [
                'brand' => 'Ford',
                'model' => 'Focus 1.0',
                'year' => 2018,
                'price_per_day' => 19.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Benzin',
                'category' => 'Malo vozilo',
                'featured' => false,
                'image' => 'uploads/cars/ford_focus1.jpg',
                'description' => 'Ford Focus 1.0 nudi spoj dinamične vožnje i male potrošnje, uz moderan dizajn i tehnologiju u kompaktnom pakovanju.',
            ],
            [
                'brand' => 'Seat',
                'model' => 'Ibiza 1.2 iTech',
                'year' => 2015,
                'price_per_day' => 16.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Benzin',
                'category' => 'Malo vozilo',
                'featured' => true,
                'image' => 'uploads/cars/seat_ibiza1.jpg',
                'description' => 'Kompaktan i ekonomičan gradski automobil, idealan za udobnu i štedljivu vožnju u urbanim sredinama.',
            ],
            [
                'brand' => 'Citroen',
                'model' => 'C3 1.4 HDi',
                'year' => 2016,
                'price_per_day' => 17.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Malo vozilo',
                'featured' => false,
                'image' => 'uploads/cars/citroen_c31.jpg',
                'description' => 'Kompaktan i ekonomičan gradski automobil, idealan za udobnu i štedljivu vožnju u urbanim sredinama.',
            ],
            [
                'brand' => 'Škoda',
                'model' => 'Fabia 1.4 TDi',
                'year' => 2018,
                'price_per_day' => 18.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Malo vozilo',
                'featured' => false,
                'image' => 'uploads/cars/skoda_fabia2.jpg',
                'description' => 'Kompaktan i ekonomičan gradski automobil, idealan za udobnu i štedljivu vožnju u urbanim sredinama.',
            ],
            [
                'brand' => 'Peugeot',
                'model' => '308 1.6 HDI',
                'year' => 2017,
                'price_per_day' => 20.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Srednje vozilo',
                'featured' => true,
                'image' => 'uploads/cars/peugeot_308_1.jpg',
                'description' => 'Peugeot 308 1.6 HDI nudi nisku potrošnju i idealan je za vozače koji žele ekonomičnost i stil u kompaktnom automobilu.',
            ],
            [
                'brand' => 'Škoda',
                'model' => 'Fabia Combi 1.4 TDi',
                'year' => 2018,
                'price_per_day' => 19.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Srednje vozilo',
                'featured' => false,
                'image' => 'uploads/cars/fabia_combi1.jpg',
                'description' => 'Praktičan i ekonomičan karavan, idealan za svakodnevnu vožnju i duža putovanja zahvaljujući prostranom prtljažniku i štedljivom dizel motoru.',
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Polo 1.2 TSI',
                'year' => 2017,
                'price_per_day' => 19.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Benzin',
                'category' => 'Srednje vozilo',
                'featured' => false,
                'image' => 'uploads/cars/vw_polo1.jpg',
                'description' => 'Volkswagen Polo 1.2 TSI nudi odličnu kombinaciju agilnosti i ekonomičnosti u kompaktnoj formi, sa turbo benzinskim motorom koji pruža dobar balans performansi i potrošnje.',
            ],
            [
                'brand' => 'Škoda',
                'model' => 'Fabia Combi 1.4 TDi',
                'year' => 2018,
                'price_per_day' => 18.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Srednje vozilo',
                'featured' => false,
                'image' => 'uploads/cars/fabia_combi2.jpg',
                'description' => 'Praktičan i ekonomičan karavan, idealan za svakodnevnu vožnju i duža putovanja zahvaljujući prostranom prtljažniku i štedljivom dizel motoru.',
            ],
            [
                'brand' => 'Renault',
                'model' => 'Megane Grandtour 1.5 DCI',
                'year' => 2016,
                'price_per_day' => 20.00,
                'transmission' => 'Manuelni',
                'fuel' => 'Dizel',
                'category' => 'Srednje vozilo',
                'featured' => true,
                'image' => 'uploads/cars/renault_megane1.jpg',
                'description' => 'Renault Megane Grandtour 1.5 DCI nudi prostranost karavana i ekonomičnost dizel motora, savršen za porodična putovanja.',
            ],
            [
                'brand' => 'Renault',
                'model' => 'Grand Scenic 1.7',
                'year' => 2022,
                'price_per_day' => 32.00,
                'transmission' => 'Automatski',
                'fuel' => 'Dizel',
                'category' => 'Veliko vozilo',
                'featured' => false,
                'image' => 'uploads/cars/renault_scenic1.jpg',
                'description' => 'Renault Grand Scenic je prostrani porodični MPV sa sedam sedišta, dizajniran za udobna putovanja i praktičnost.',
            ],
            [
                'brand' => 'Škoda',
                'model' => 'Octavia 2.0 TDi',
                'year' => 2020,
                'price_per_day' => 27.00,
                'transmission' => 'Automatski',
                'fuel' => 'Dizel',
                'category' => 'Veliko vozilo',
                'featured' => false,
                'image' => 'uploads/cars/skoda_octavia1.jpg',
                'description' => 'Škoda Octavia 2.0 TDI je pouzdan i prostran automobil sa snažnim dizel motorom, odličan za duga putovanja i svakodnevnu upotrebu.',
            ],
        ]);
    }
}
